{% set version = '0.1.1' %}

package:
  name: jupyter_nbextensions_configurator
  version: {{ version }}

source:
  git_url: https://github.com/Jupyter-contrib/jupyter_nbextensions_configurator.git
  git_tag: {{ version }}

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - jupyter_core
    - nbconvert
    - notebook >=4.0
    - pyyaml
    - tornado
    - traitlets

test:
  imports:
    - jupyter_nbextensions_configurator
    - jupyter_nbextensions_configurator.application
    - jupyter_nbextensions_configurator.notebook_compat
    - jupyter_nbextensions_configurator.notebook_compat.nbextensions
    - jupyter_nbextensions_configurator.notebook_compat.serverextensions
    - jupyter_nbextensions_configurator.notebook_compat._compat
    - jupyter_nbextensions_configurator.notebook_compat._compat.nbextensions
    - jupyter_nbextensions_configurator.notebook_compat._compat.serverextensions

  commands:
    - jupyter nbextensions_configurator --help
    - jupyter nbextensions_configurator enable --help
    - jupyter nbextensions_configurator disable --help

about:
  summary: A server extension for jupyter notebook providing configuration interfaces for notebook extensions (nbextensions).
  home: https://github.com/Jupyter-contrib/jupyter_nbextensions_configurator
  license_file: LICENSE.txt
  license: BSD 3-clause

extra:
  recipe-maintainers:
    - jcb91

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
